name: impressionist-stylegan-cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  - cpuonly

  - pytorch=2.5.1
  - torchvision
  - torchaudio

  - pillow
  - matplotlib
  - tqdm
  - ipykernel
  - kornia
  - hdbscan
  - scikit-learn
  - umap-learn
  - pandas
  - torchmetrics
  - transformers=4.51.3

  - pip:
      - torch-fidelity
